comment:
 
  footer: "\
    ---\n\n
    > &nbsp; &#9; &nbsp; &#9;  &nbsp; &#9;  &nbsp; &#9; Be sure to [join the community](http://slack.layer5.io), if you haven't yet and please leave a :star: [star on the project](../stargazers) :smile:
    "

labels:
  
  - name: issue/remind
    labeled:
      issue:
        body: Checking in... it has been awhile since we&#39;ve heard from you on this issue. Are you still working on it? Please let us know and please don&#39;t hesitate to contact a [MeshMate](https://layer5.io/community/meshmates/) or any other [community member](https://layer5.io/community/members) for assistance.
        action: open
      pr: 
        body: Checking in... it has been awhile since we&#39;ve heard from you on this issue. Are you still working on it? Please let us know and please don&#39;t hesitate to contact a [MeshMate](https://layer5.io/community/meshmates/) or any other [community member](https://layer5.io/community/members) for assistance.
        action: open
  - name: issue/dco
    labeled:
      issue:
        body: "🚨 Alert! Git Police! We couldn’t help but notice that one or more of your commits is missing a sign-off. _A what?_ A commit sign-off (your email address).\n\n
         To amend the commits in this PR with your signoff using the instructions provided in the DCO check above. \n\n
         To configure your dev environment to automatically signoff on your commits in the future, see [these instructions](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)."
        action: open
      pr:
        body: "🚨 Alert! Git Police! We couldn’t help but notice that one or more of your commits is missing a sign-off. _A what?_ A commit sign-off (your email address).\n\n
         To amend the commits in this PR with your signoff using the instructions provided in the DCO check above. \n\n
         To configure your dev environment to automatically signoff on your commits in the future, see [these instructions](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)."
        action: open
  - name: duplicate
    labeled:
      issue:
        body: Thank you @{{ issue.user.login }} for suggesting this but this issue already exists. Therefore, we are closing this issue.
        action: close
      pr:
        body: Thank you @{{ pull_request.user.login }} for contributing but this PR already exists. Therefore, we are closing this.
        action: close
  - name: invalid
    labeled:
      pr:
        body: Thank you @{{ pull_request.user.login }} for suggesting this. Please follow the pull request templates.
        action: close
  - name: proposal
    labeled:
      issue:
        body: Thank you @{{ issue.user.login }} for suggesting this issue. 
  - name: wontfix
    labeled:
      issue:
        body: @{{ issue.user.login }} This will not be worked on but we appreciate your contribution.
        action: close
      pr:
        body: @{{ issue.user.login }} This will not be worked on but we appreciate your contribution.
        action: close
      
 
